### ISSUE TITLE
UI reload resets monitored groups

### ISSUE THREAD

**Issue by manticode** [kvakvs/BuffomatClassic#1]
when doing /reload, groups selected to monitor are reset to all groups

preferred solution:

keep selected groups consistent across UI reloads

If possible, reset only when exiting raid

**Comment by kvakvs** [comment]
Monitored groups are now saved as character config.
Reloading while in party seems to keep settings saved (as intended)
Leaving the party seems to clear the settings (as intended)
You can switch to Beta channel in Curseforge and look for the file to download (1.9-b at https://www.curseforge.com/wow/addons/buffomat-classic, do not get 1.9 alpha)
