### ISSUE TITLE
Ignore single Players

### ISSUE THREAD

**Issue by Willy130683** [kvakvs/BuffomatClassic#10]
Hi,

first I want to say thanks for reviving this addon. What I was missing in the original is an option to ignore single players. For example when iam raiding with my mage and the ferals will cancel their int buff, buffomat will Popup to buff them. Tonight even a ret was cancelling his int buff ;)
So I would really appreciate if you could look into implementing an single player ignore option.

**Comment by kvakvs** [comment]
That would be a separate ignore list per group buff.
Something like a tiny button to ignore the targeted person for the selected buff.
And then it needs a way to review ignore list and clear it.

**Comment by Willy130683** [comment]
Yeah right, a Button next to the person in the buff view. And a new view to show ignored players per buff where you can reset the ignore could be great. 
But a simpler solution could be to just save the ignores for this session(until logout/reload ui) and just have one simple menu entry to clear all ignores manually. Just hitting the ignore button for a person every raid, would still be a big improvement to the current state, at least in my view.

**Comment by kvakvs** [comment]
Alpha version 1.9.5 uploaded today, get at your own risk :)
Can force cast on players (feature existed before) and new button next to it - can exclude players.
![image](https://media.forgecdn.net/attachments/thumbnails/353/106/310/172/include-ignore.png)

**Comment by Willy130683** [comment]
Hi thanks, I didn't even realize that there are more options on the right because i don´t have the window setup that wide and there is no horizontal scrollbar ;)
But I found it and tested it with just my char and the ignore seems to work properly, thanks for that.
The kind of funny thing is I locked into it by my self and have a working version since saturday, completley diffrent approach than yours, but it worked for me also ;)
Because getting startet with lua and addon development was a challange in of it self my implementation is not as well integrated as yours.
But one thing i did on the site was adding the target of the next cast back to the cast button there was event a comment with the code for that, perhaps you can add that back in the main project, here is a link to the commit on my fork: https://github.com/Willy130683/BuffomatClassic/commit/20ff617f0bec38d9850aee88f45a91be9460cd30

**Comment by Willy130683** [comment]
So after i testet it in some raids it works great for me, thank you.
