### ISSUE TITLE
Druid issues:  (WotLK) Gift of the Wild and Mark of the Wild

### ISSUE THREAD

**Issue by LandonStewart** [kvakvs/BuffomatClassic#105]
While trying on solo, automatic or in a group the _Gift of the Wild_ keeps showing up no matter if I have GotW or MotW buff or not.  It should offer _Mark of the Wild_ if I'm not in a group I think.  And it should know I already have GotW of course.

<img width="255" alt="Screenshot 2022-11-03 at 6 57 21 PM" src="https://user-images.githubusercontent.com/2685312/199868993-63eb6486-092f-401e-a238-2bc73cb03f10.png">

This happens if it's set to Self-cast only or Buff party (with classes to buff selected although that doesn't matter in WotLK).

It's like it doesn't know the difference between _Mark of the Wild_ and _Gift of the Wild_ and it doesn't know that Gift of the Wild is already buffed.

**Comment by Kruemmelkeks** [comment]
The same also happens to my Mage and Priest:
![image](https://user-images.githubusercontent.com/37963123/200115277-e94ad17b-419f-4a16-b0dc-9c92bff41c1b.png)

Those are my current settings (localized in German):
![image](https://user-images.githubusercontent.com/37963123/200115380-0e092ae1-9bf2-4540-81f4-100736a473ef.png)

**Comment by Teclini** [comment]
The same also happens to my Druid.

**Comment by LandonStewart** [comment]
It looks like this is fixed with the latest update (11/5/2022 BuffomatClassic 2022.11.0.1).

Thank you!
