### ISSUE TITLE
[Wrath] Conjure Mana Gem always visible

### ISSUE THREAD

**Issue by olamm2k** [kvakvs/BuffomatClassic#114]
Most likely due to the C_Container changes in 3.4.1 (https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes), Conjure Mana Gem is always showing, even when it has full charges.

![image](https://user-images.githubusercontent.com/179024/213182321-31a9340f-f572-488d-9bec-f3bac790a1ef.png)

**Comment by jdelvare** [comment]
Duplicate of bug #113.

**Comment by jdelvare** [comment]
Fixed, can be closed.
