### ISSUE TITLE
Classic HC - Shaman - Rockbiter Weapon buff no registering

### ISSUE THREAD

**Issue by Hessutar** [kvakvs/BuffomatClassic#118]
Hello.

Am I missing something or is this a bug?

For some reason Rockbiter Weapon is not registering and is asking me to buff my weapon constantly.
I've set limit for 5 minute and under buffs to notify rebuffing after 30sec, but it seems to have no effect.

![Näyttökuva 2023-11-12 173108](https://github.com/kvakvs/BuffomatClassic/assets/5693510/925d3a4e-de3a-4d61-b855-8d287d8866ce)

Addon has been working flawlessly otherwise!

**Comment by kvakvs** [comment]
Which rank is rockbiter, i do not have classic shamans ready to try it. So might need to level one and hope its some early levels.

Problem is that unlike other shaman weapon enchantments, rockbiter is a script, which gives some totally different enchantment than the spell database on wowhead shows. I had to fiddle with every rank before.

**Comment by Hessutar** [comment]
Heya! Atleast ranks 1 and 2. Is there anyway I can help solving out the real ids?

**Comment by kvakvs** [comment]
Uploaded an update, please give it a look
