### ISSUE TITLE
2024.3.1 is missing LibDataBroker-1.1 and LibDBIcon-1.0

### ISSUE THREAD

**Issue by mooreatv** [kvakvs/BuffomatClassic#121]
Message: Interface/AddOns/BuffomatClassic/Src/Buffomat.lua:298: Cannot find a library instance of "LibDataBroker-1.1".
Time: Fri Mar 29 13:18:16 2024
Count: 1
Stack: Interface/AddOns/BuffomatClassic/Src/Buffomat.lua:298: Cannot find a library instance of "LibDataBroker-1.1".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/BuffomatClassic/Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BuffomatClassic/Src/Buffomat.lua"]:298: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibDataBroker-1.1"."

Message: Interface/AddOns/BuffomatClassic/Src/Ui/Options.lua:15: Cannot find a library instance of "LibDBIcon-1.0".
Time: Fri Mar 29 13:18:16 2024
Count: 1
Stack: Interface/AddOns/BuffomatClassic/Src/Ui/Options.lua:15: Cannot find a library instance of "LibDBIcon-1.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/BuffomatClassic/Ace3/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/BuffomatClassic/Src/Ui/Options.lua"]:15: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibDBIcon-1.0"."

**Comment by kvakvs** [comment]
It is not missing, it is misconfigured. Fixing it right now.

**Comment by mooreatv** [comment]
Thanks! so new release soon with that fix?

**Comment by mooreatv** [comment]
also while at it can you update the toc so it works without needing "load out of date" please - tia

## Interface: 11501

in your classic toc

**Comment by kvakvs** [comment]
The fix is out a day ago in 2024.3.2
I will release that minor version update later, will be away till Friday.

**Comment by mooreatv** [comment]
Thanks it showed up on curse after my comment - but now https://github.com/kvakvs/BuffomatClassic/issues/123
