### ISSUE TITLE
Problem - Buffs are suggested although they are already there

### ISSUE THREAD

**Issue by GuardyCWMW** [kvakvs/BuffomatClassic#125]
Hello! 

Unfortunately I have a problem with Buff-o-Mat since Cata.
Pure selfbuffs work without any problems. But stamina and shadow protection do not work. It is always displayed for buffing. No matter if I (or in party also all others) have the buffs or not. - Does anyone else have the problem or even better... a solution?

**Comment by kvakvs** [comment]
My priest is level 80 and i was fixing this bug yesterday. Tried self-buffing and it seemed to work. You don't get newer ranks of fortitude later, don't you? Might be talent ranks change the spell id of the buff or something.

**Comment by kvakvs** [comment]
Please give a try to 2024.5.4

**Comment by GuardyCWMW** [comment]
DREAMY! Thank you very much! Now it seems to be working! Unfortunately, I'm not very familiar with programming add-ons and had already looked at where the problem could have been. As you can see from my request, I have not been able to solve it. :D 

Thank you very much for the update!

**Comment by kvakvs** [comment]
Please check latest version 2024.5.4

**Comment by GuardyCWMW** [comment]
> Please check latest version 2024.5.4

Yes,it works. (not testet in group, yet). Thanks!
