### ISSUE TITLE
The addon causes macro text input to reset

### ISSUE THREAD

**Issue by str8Astud3nt** [kvakvs/BuffomatClassic#128]
With the addon enabled, attempting to modify any macro will cause the modified text to revert every few seconds making it nearly impossible to modify or create new macros.

Issue occurred on "Buffomat Classic 2024.7.0" with game version 1.15.3.55563 (classic SoD)

**Comment by kvakvs** [comment]
This is the way addon works, it modifies the macro text every time the situation changes.
Find a moment when you aren't buffing, to modify your other macros.

**Comment by Shiftard** [comment]
> This is the way addon works, it modifies the macro text every time the situation changes. Find a moment when you aren't buffing, to modify your other macros.

This isn't the normal Buffomat macro, this is EVERY macro. Can confirm this occurs and is a pain in the arse.

**Comment by mygitjuan** [comment]
I have not been able to edit my macros for 2 weeks until I found out it was buffomat. So please as the others say, "This isn't the normal Buffomat macro, this is every macro". Please check this issue.

**Comment by kvakvs** [comment]
Buffomat deactivates self if macro window is open. Is this still a problem?

**Comment by jomysan** [comment]
up for this

**Comment by inthemixmike** [comment]
This is still a problem.  I'm standing in town, ungrouped, and "buffing in the world disabled" and I cannot create or edit macros.  They get deleted as Im typing them.

**Comment by kvakvs** [comment]
I've added a check for macro window open many months ago. Apparently it was detecting only for my wow version (beginning of Cataclysm Classic) and some phase 3 or 4 of the seasonal classic. And now it doesn't detect properly, and i do not have a subscription or an installed wow, so it is kinda problematic to fix.
