### ISSUE TITLE
Macros rolling back/not saving

### ISSUE THREAD

**Issue by Larsy93** [kvakvs/BuffomatClassic#132]
if buffomat is enabled and I'm typing in a new macro every few seconds all my text will dissapear and it will go back to how it was before. Any macro, it does something that affects writing macros on an interval somehow.

**Comment by kvakvs** [comment]
This was contributed earlier today, did you update and does it still not work? https://github.com/kvakvs/BuffomatClassic/pull/131

**Comment by Larsy93** [comment]
Updated, still does not work.

**Comment by Larsy93** [comment]
Also the macro is not updating in the latest version, on my priest for example it said inner fire for like 5 seconds after applying it and after applying power word fortitude on me it shows that power word fortitude is still a remaining action in the macro even tho addon window says "Nothing to do" so something else broke and it did not fix the initial issue.
