### ISSUE TITLE
No more .lua errors, but macro is fully broken.

### ISSUE THREAD

**Issue by Larsy93** [kvakvs/BuffomatClassic#133]
Always shows inner fire on my priest, never updates no matter what.

**Comment by kvakvs** [comment]
Buffomat does update if you hide/show it (Assign a shortcut key) or at some moment later (it checks now and then).
If i revert that wipemacro line change, then it will start doing that funny macro reset again when the macro window is open

**Comment by Larsy93** [comment]
> Buffomat does update if you hide/show it (Assign a shortcut key) or at some moment later (it checks now and then). If i revert that wipemacro line change, then it will start doing that funny macro reset again when the macro window is open Well then the bug is still here. Not wiping the macro and pressing the macro shortcut keeps casting the macro repeatedly even if the buff is not necessary.

your last fix was enough. it does not require the first one. both at the same time and addon is broken.

**Comment by kvakvs** [comment]
Please have a look again with 2024.12.3, this should solve it.

**Comment by Larsy93** [comment]
yep, but now last version on curseforge says 2024.7.1

**Comment by Larsy93** [comment]
With the latest version the macro resets are back again.. wth

**Comment by Larsy93** [comment]
only the one on curseforge tho I believe. the one from github seems fine. something weird happend with version numbers.
