### ISSUE TITLE
TBC: Big checklist

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/BuffomatClassic#18]
## Classes

- [x] Rogue (poisons)
- [x] Priest
- [x] Mage
- [x] Paladin
- [x] Druid
- [x] Shaman
- [x] Warrior
- [x] Hunter
- [x] Warlock

## Consumables

- [x] Elixirs
- [x] Flasks
- [x] Food Buff Consumables: Fisherman's Feast, Spicy Hot Talbuk, Roasted Clefthoof, Ravager Dog, Blackened Basilisk, Golden Fish Sticks, Grilled Mudfish

**Comment by padmanek** [comment]
Warlock missing:
-Fel Armor
-Spellstone

Also, Demon Skin is a starter buff that only has Rank 1 and Rank 2 available at lvl 10.
From lvl 20 Warlocks get access to Demon Armor and will never use Demon Skin in their life again. It can safely be hidden from lvl 20.

**Comment by kvakvs** [comment]
Added that conjure spell and will hide demon skin at 21 (giving player time to reach the trainer)
Will upload later with TBC food update.

**Comment by kvakvs** [comment]
Added warlock and food buffs in 2021.5.1
