### ISSUE TITLE
Smarter resurrecting

### ISSUE THREAD

**Issue by manticode** [kvakvs/BuffomatClassic#2]
Currently there appears to be no order when resurrecting after a wipe.

Prefer to prioritise resurrecting priests and shamans (and paladins) before other classes.

**Comment by kvakvs** [comment]
The README/features claims to do exactly that. I will have a look what it actually does.

**Comment by kvakvs** [comment]
Sorting seems to be working.
Needs more extensive testing in a very bad dead 5man party or a raid.

**Comment by kvakvs** [comment]
Testing tonight looked good to me
