### ISSUE TITLE
Mana Ruby shows twice

### ISSUE THREAD

**Issue by godsyn** [kvakvs/BuffomatClassic#20]
![image](https://user-images.githubusercontent.com/508678/116331948-d11de200-a79e-11eb-92e4-24e4b691ad00.png)
Mana Ruby shows twice, instead of showing / casting Mana Ruby and Mana Citrine
I'd like to have both in my bags at all times. (this worked in previous versions)

**Comment by kvakvs** [comment]
I noticed last night too. Thanks for reporting, will have this done soon.

**Comment by kvakvs** [comment]
Fixing it in the following way
If the player knows Emerald (TBC level 68), second option will be to conjure Ruby
If the player knows Ruby, second option will be to conjure Citrine
For lower level, there will be no second option

**Comment by kvakvs** [comment]
Fixed in 2021.4.5
