### ISSUE TITLE
Mage : doesn't create mana ruby if critine exists.

### ISSUE THREAD

**Issue by godsyn** [kvakvs/BuffomatClassic#21]
When selecting "conjure mana ruby" and "conjure mana critine" from the list of spells, 

The result is it will only check if one exists, and show "nothing to do". 

To reproduce:
Select both gems
![image](https://user-images.githubusercontent.com/508678/116498621-24b02e80-a878-11eb-9ec3-3680125ab6ca.png)

Create one mana critine gem (via B`oM or manually).
No mana ruby is suggested.

**Comment by kvakvs** [comment]
As you may have guessed, i have no mage on live Classic. But i am testing on TBC level 61 mage and level 70 mage.
Let me have a look...

**Comment by kvakvs** [comment]
Uploaded 2021.4.6

**Comment by godsyn** [comment]
Works wonderfully!
