### ISSUE TITLE
rockbiter weapon rank 3 not recognized

### ISSUE THREAD

**Issue by EdgarFriendly** [kvakvs/BuffomatClassic#31]
Version: 2021.5.9-162debdb

While rockbiter weapon rank 1 and 2 work fine, BOM doesn't recognize when rank 3 ist applied on the mainhand weapon and wants to reapply it even if it's already on the weapon.

Am I doing something wrong? Anything I can provide to solve the issue?

**Comment by kvakvs** [comment]
rockbiter new enchantment ids in TBC: added
