### ISSUE TITLE
Fel Armor missing from Warlock buffs.

### ISSUE THREAD

**Issue by padmanek** [kvakvs/BuffomatClassic#34]
Title. 
The most important warlock self buff in TBC. Acquired on lvl 62.
Reported this 1.5 month ago https://github.com/kvakvs/BuffomatClassic/issues/18#issuecomment-830842957

**Comment by kvakvs** [comment]
I have added the fix, but the release will be delayed some days, i am also looking for performance issue in large raids.

**Comment by kvakvs** [comment]
Please have a look at 2021.5.12-DEBUG in BETA channel
