### ISSUE TITLE
Ensure buffing warlock pets (pets in general) works

### ISSUE THREAD

**Issue by kvakvs** [kvakvs/BuffomatClassic#38]
Hey, are you able to add support to buff warlock pets?

Need that extra minmax buff on the felguard with my motw :D

**Comment by farske** [comment]
It seems it doesn't let me buff hunter pets in my party either, so yeah maybe an examination at all pets.

**Comment by kvakvs** [comment]
Buffing pets kinda works? Closing this, but feel free to reopen if it doesn't work.

**Comment by farske** [comment]
I gave it a test with hunters and warlocks.

It just doesnt appear for some reason.
I'll grab a little gif next time I'm on.

**Comment by farske** [comment]
I gave it a test with hunters and warlocks.

It just doesnt appear for some reason.
I'll grab a little gif next time I'm on.

**Comment by kvakvs** [comment]
Enable group buff for the buff you're testing, click two silhoutettes 👥
Then in the right side after all classes and tanks, click 🐯 tiger face to enable buffing pets.

**Comment by farske** [comment]
I grabbed my Hunter mate.
My settings: https://i.imgur.com/HcsOyTY.png
My buff prompts: https://i.imgur.com/gNeKAyY.png
Pet has no buff: https://i.imgur.com/pQnwNrB.png
Even shown with group buffs: https://i.imgur.com/1IGZUTy.png

Does this not work with other party members pets buffs?

**Comment by kvakvs** [comment]
I certainly remember that it prompts me to buff pets in dungeons. I will need to double check the code.
Thanks for the detailed demo.

P.S. you can Win+Shift+S to grab an area screenshot and paste the copied picture directly in your Github comments.
