### ISSUE TITLE
Missing food Grilled Mudfish

### ISSUE THREAD

**Issue by trying-to-function** [kvakvs/BuffomatClassic#41]
Please add:
Grilled Mudfish: https://tbc.wowhead.com/spell=33293/grilled-mudfish

It is the same as [Warp Burger](https://tbc.wowhead.com/spell=33288/warp-burger).

Possible to merge the two?

**Comment by kvakvs** [comment]
All food buffs of same type are merged, Buffomat will choose whatever you have in your bag.

Should be supported in the next release, i added it.
