### ISSUE TITLE
Chat spam as a result of using macro too quickly.

### ISSUE THREAD

**Issue by godsyn** [kvakvs/BuffomatClassic#45]
When spamming buffomat macro (I've shift + mouse-wheel down bound to buffomat) you spam the last chat with "rerror" (/say by default).

No other addons enabled in screenshot.

Edit:

Version: BuffomatClassicTBC-2021.6.5
Reverted to BuffomatClassicTBC-2021.6.3, and issue was resolved.

![image](https://user-images.githubusercontent.com/508678/123518694-0a76af00-d675-11eb-8b1b-a78b42bd7010.png)

**Comment by kvakvs** [comment]
This should be fixed in most recent update. Is this error still present? Please see version 2021.6.6

**Comment by godsyn** [comment]
Fixed in 6.6. thank you
