### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by trying-to-function** [kvakvs/BuffomatClassic#47]
When logging into the game this error pops up:

```
Message: Binding header BUFFOMATHEADER is defined more than once in Interface\AddOns\BuffomatClassic\Bindings.xml
Time: Tue Jun 29 08:22:17 2021
Count: 2
```

**Comment by kvakvs** [comment]
This is some old version bug, i fixed it weeks ago. Are you using the latest version?

**Comment by trying-to-function** [comment]
I update my addons everyday via [CurseBreaker](https://github.com/AcidWeb/CurseBreaker) so I thought it was. but you helped me directly via discord and I must have been using that version ever since. I updated it and I'm no longer getting an error. Thank you! Sorry about the unneeded issue.
