### ISSUE TITLE
Enhancement: #showtooltip functionality for macro

### ISSUE THREAD

**Issue by Anonomit** [kvakvs/BuffomatClassic#61]
Changing the BOM.MACRO_ICON (line 55: src/Bom.lua) to "inv_misc_questionmark" enables #showtooltip functionality on the macro while buffing. I think this should be the default, but it would be nice to at least have a config option to make this change.

Version: 2021.10.3-5077c00b
Build: 2.5.3, 41812, Jan  7 2022, 20503

**Comment by kvakvs** [comment]
I don't get it how icon affects the use of `#showtooltip`.
`#showtooltip` shows icon for the first spell in your macro, or can also `#showtooltip Spell Name`

Also I do not have macro on action bars, you can bind a convenient key to the macro and use the macro directly from they keybinds.

**Comment by Anonomit** [comment]
The "inv_misc_questionmark" icon is special for macros, and will inherit the icon from the first spell/item/whatever being used by the macro when #show or #showtooltip are used. Here's my use case since I've changed the icon:

When nothing needs to be buffed: Macro on my hotbar shows "Ability_Druid_DemoralizingRoar" tooltip.
When mark/gift of the wild needs to be buffed: Macro on my bar shows me whether it's mark or gift. I can decide whether to buff based on that.
When thorns needs to be buffed: Macro on my bar shows thorns. Swap to thorns gear. Buff. Swap back.


I place the macro on my actionbar next to my manual buff abilities, my gear swap macros, and itemrack. I keep thorns on tanks, and I have 3 pieces of T1 in my bags so the thorns will last for 15 minutes. Obviously I only want to equip these items when I buff, and then I equip something else for combat. This is why I need to know if the buff I'll be casting is thorns. Even if I'm using a hotkey to buff, having the button visible next to my other buff abilities (and next to the button that equips thorns gear) is important for me.

I think this is worth having as a config option at the very least. I also think it should be the default behaviour.

**Comment by kvakvs** [comment]
I've made the changes will try it later today and can upload

**Comment by kvakvs** [comment]
Just tried it and it works. Thanks for the tip again :) Uploaded 2021.1.1
