### ISSUE TITLE
Request:  Add spirit tap config item and logic change

### ISSUE THREAD

**Issue by Grokii-coder** [kvakvs/BuffomatClassic#66]
Request:  Add spirit tap config item and logic change

The 'Spirit Tap' talent for priest doubles spirit, but the return is greatly diminished while inside the 5 second rule.  I'm leveling a priest and love the addon, but once combat is done I get Spirit Tap and also see a popup from Buffomat that I need to recast a buff.  I usually  immediately do cast the buff, but then regret it since Spirit Tap is running.  It would be wonderful to give a config option to Buffomat to not prompt to cast buffs while under the effects of Spirit Tap.

**Comment by kvakvs** [comment]
Added a quick option, please have a look at 2022.2.1

**Comment by Grokii-coder** [comment]
I updated the addon, enabled the setting, and it works as requested.  Thank you!

**Comment by Grokii-coder** [comment]
Sorry for the feature creep, but after using it I'm encountering the opposite issue:  Full mana with Spirit Tap active and wishing BOM would allow me to cast buffs.  I need to click Spirit Tap off to allow BOM to prompt me to rebuff Inner Fire.

I propose modifying the configuration from a checkbox to a slider from 0 to 100 with the default value at 0.  Then modify the spirit tap if statement in TaskScan.lua to compare % of current mana to the value chosen in the slider.  If current mana % is less than slider, then return false.

Default value of the slider would be 0, and then people could choose the mana % to suppress BOM while under spirit tap.

I see that  you already collect bomCurrentPlayerMana which is compared to spell cost to see if spells can be cast.  Would it cause overhead to also collect max player mana and calculate the percentage?

**Comment by kvakvs** [comment]
I had a thought that I should really check the mana. I forgor 💀

**Comment by kvakvs** [comment]
The current options code is the legacy code from old addon creator, it is easy to add a checkbox but slider would take more effort. I am dreading the need to go and add a slider. Shall we just hardcode it at 90% or something?

**Comment by Grokii-coder** [comment]
Yes, hardcode 90 would be great.

**Comment by kvakvs** [comment]
I have entirely reworked the options page and options menu is using some new tech too, and added a slider. I will upload a beta preview soon, feel free to test it. I raided last night with it, having only 1 script error but that was since fixed.
