### ISSUE TITLE
[TBC] Phase 3 new flasks tracking.

### ISSUE THREAD

**Issue by padmanek** [kvakvs/BuffomatClassic#70]
Hello,
With the addition of new flasks acquired with Mark of the Illidari in the latest TBC patch I'd like to request tracking of the following consumables:

- Shattrath Flask of Relentless Assault
- Shattrath Flask of Pure Death
- Shattrath Flask of Fortification
- Shattrath Flask of Blinding Light
- Shattrath Flask of Mighty Restoration
- Shattrath Flask of Supreme Power

All can be found here https://tbc.wowhead.com/search?q=Shattrath+Flask

Thanks!

**Comment by kvakvs** [comment]
Added shattrath flasks a few days ago.
