### ISSUE TITLE
[TBC] Feature Request - Find Fish (tracking)

### ISSUE THREAD

**Issue by LandonStewart** [kvakvs/BuffomatClassic#71]
I noticed the "Find Fish" tracking is not an option in the Spells. 

<img width="295" alt="Screen Shot 2022-02-19 at 11 10 15 PM" src="https://user-images.githubusercontent.com/2685312/154832442-8839997f-bfaa-47de-8b53-5475f181d656.png">
 
Can this be added?  

Also - it'd be cool if it was automatic like when Paladins with Crusader Aura mount but instead of mounting it'd trigger when you equip a fishing pole.

**Comment by kvakvs** [comment]
Find fish was added a couple weeks ago
