### ISSUE TITLE
Missing: Scroll of Spirit IV

### ISSUE THREAD

**Issue by jdelvare** [kvakvs/BuffomatClassic#82]
I like to use Scroll of Spirit IV when doing lower level dungeons and raids, so I added support for it.

Please consider applying this patch:
[buffomat-add-spirit-IV.patch.txt](https://github.com/kvakvs/BuffomatClassic/files/8694782/buffomat-add-spirit-IV.patch.txt)

**Comment by jdelvare** [comment]
Patch updated to apply to the latest version of Buffomat:
[buffomat-add-spirit-IV-2.patch.txt](https://github.com/kvakvs/BuffomatClassic/files/9138661/buffomat-add-spirit-IV-2.patch.txt)

**Comment by kvakvs** [comment]
Added thanks. Will be uploaded with the release after raid testing
