### ISSUE TITLE
Button says 'buffing in the world disabled'

### ISSUE THREAD

**Issue by Scuffedaf** [kvakvs/BuffomatClassic#87]
Red button says: 'buffing in the world disabled', when in instance/raid it says: 'buffing in instance disabled'. How can I make the addon work? It worked fine before last update...

**Comment by Scuffedaf** [comment]
I think it's fixed, thank you !!

**Comment by kvakvs** [comment]
I have a fix for this in upcoming release.
The problem in the current release is that if you have a fresh install, or delete settings, it will have all checkboxes cleared.
