### ISSUE TITLE
..\AddOns\BuffomatClassicTBC\Src/Buffomat.lua line 874:    attempt to index global 'self' (a nil value)

### ISSUE THREAD

**Issue by dieck** [kvakvs/BuffomatClassic#89]
Hi!

I encountered an error 
..\AddOns\BuffomatClassicTBC\Src/Buffomat.lua line 874:  attempt to index global 'self' (a nil value) 

`Date: 2022-05-23 18:30:34
ID: -2
Error occured in: Global
Count: 2
Message: ..\AddOns\BuffomatClassicTBC\Src/Buffomat.lua line 874:
   attempt to index global 'self' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@BuffomatClassicTBC\Src/Buffomat.lua"]:874: FastUpdateTimer()
   [string "@BuffomatClassicTBC\Src/TaskScan.lua"]:2110: AddMemberToSkipList()
   [string "@BuffomatClassicTBC\Src/Events.lua"]:244:
      BuffomatClassicTBC\Src/Events.lua:215
   [string "=[C]"]: ?
   [string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29:
      ...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   [string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: Fire()
   [string "@Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120:
      ...ace\AddOns\Attune\Libs\AceEvent-3.0\AceEvent-3.0.lua:119
   [string "=[C]"]: ?
   [string "=[C]"]: CastSpellByName()
   [string "@..\FrameXML\ChatFrame.lua"]:1200: ?()
   [string "@..\FrameXML\ChatFrame.lua"]:4880:
      ..\FrameXML\ChatFrame.lua:4846
   [string "=[C]"]: ChatEdit_ParseText()
   [string "@..\FrameXML\ChatFrame.lua"]:4563:
      ..\FrameXML\ChatFrame.lua:4562
   [string "=[C]"]: ChatEdit_SendText()
   [string "@..\FrameXML\ChatFrame.lua"]:2944:
      ..\FrameXML\ChatFrame.lua:2937
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "=[C]"]: UseAction()
   [string "@..\FrameXML\SecureTemplates.lua"]:343: handler()
   [string "@..\FrameXML\SecureTemplates.lua"]:625:
      ..\FrameXML\SecureTemplates.lua:569
   [string "=[C]"]: ?
   [string "@..\FrameXML\SecureHandlers.lua"]:266:
      ..\FrameXML\SecureHandlers.lua:263
   [string "=[C]"]: ?
   [string "@..\FrameXML\SecureHandlers.lua"]:296:
      ..\FrameXML\SecureHandlers.lua:279
   [string "=(tail call)"]: ?
Locals:
None
AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  ACP, v3.5.7 
  AtlasLootClassic, vv2.4.4-bcc
  AtlasLootClassicData, vv2.4.4-bcc
  AtlasLootClassicDungeonsAndRaids, vv2.4.4-bcc
  Attune, v253
  BagBrother, v
  Bagnon, v9.2.0
  Bartender4, v4.11.1
  BuffomatClassicTBC, v2022.5.1-71a32cfe
  CheeseSLS, v20220213
  Clique, vv3.1.3
  CoolDownWatcher, v1.12
  DBMCore, vb1468f5
  DBMStatusBarTimers, vb1468f5
  DBMVPVEM, v9d95365
  Dismounter, v1.2.1
  ExtendedCharacterStats, v2.12.0
  FishingBuddy, v0.7.5.5
  GoogleSheetDKP, v20210123
  Guildbook, v4.994
  InFlightLoad, v1.13.005
  ItemRack, v
  MikScrollingBattleText, v5.7.152
  MRT, v4610
  NovaWorldBuffs, v2.28
  NugRunning, v9.2.1
  OmniCC, v9.2.0
  Pawn, v2.5.38
  PitBull4, vv4.3.3-classic
  Plater, vPlater-v350-BCC
  Prat30, v3.9.1
  Prat30Libraries, v
  Prio3, v20210521
  Quartz, v3.6.9
  Questie, v6.10.3
  Raidinfos, v20210521
  RaidSummon, v4.0.2
  Recount, vv2.5.3c
  Reputable, v1.29-bcc
  RollTrackerClassic, v2.21-bcc
  Scrap, v9.1.2
  ScrapMerchant, v
  SoulSort, v1.1 TBC
  Spy, v1.1.2
  Stubby, v2.5.6772 (SwimmingSeadragon)
  SvensBamAddon, v1.10.4
  ThreatClassic2, v2.44
  TitanClassic, v1.5.2.20504
  TitanClassicAmmo, v1.5.2.20504
  TitanClassicBag, v1.5.2.20504
  TitanClassicClock, v1.5.2.20504
  TitanClassicGold, v1.5.2.20504
  TitanClassicLocation, v1.5.2.20504
  TitanClassicLootType, v1.5.2.20504
  TitanClassicPerformance, v1.5.2.20504
  TitanClassicRegen, v1.5.2.20504
  TitanClassicRepair, v1.5.2.20504
  TitanClassicVolume, v1.5.2.20504
  TitanClassicXP, v1.5.2.20504
  TomTom, vv3.0.6
  TotemTimers, v2.2.2
  TradeSkillMaster, vv4.11.29
  TradeSkillMasterAppHelper, vv4.0.20
  WaterDispenser, v1.10
  WeakAuras, v4.0.0
  WeakAurasArchive, v4.0.0
  WeakAurasOptions, v4.0.0
  BlizRuntimeLib_enUS v2.5.4.20504 <none>
  (ck=707)
`

I assume it's due to self not being available on function BOM.FastUpdateTimer() somehow?
Tried using   buffomatModule.lastUpdateTimestamp = 0, that seems to fix it.

**Comment by kvakvs** [comment]
This might be solved with recent updates?
I did not observe this for a long time now.
