### ISSUE TITLE
Checking Elixir of Major Agility also checks Elixir of Mighty Agility

### ISSUE THREAD

**Issue by jdelvare** [kvakvs/BuffomatClassic#99]
Likewise, checking Adept's Elixir also checks Spellpower Elixir. This is caused by Elixir of Major Agility and Adept's Elixir being accidentally defined with the spell ID of their WotLK counterparts. I'll attach a patch fixing this.

**Comment by jdelvare** [comment]
[Buffomat-fix-Spellpower-elixir.patch.txt](https://github.com/kvakvs/BuffomatClassic/files/9579244/Buffomat-fix-Spellpower-elixir.patch.txt)

**Comment by kvakvs** [comment]
In fact, adept's elixir drink effect spell id is reused in wotlk for spellpower elixir!
https://www.wowhead.com/wotlk/spell=33721/spellpower-elixir
https://www.wowhead.com/tbc/spell=33721/adepts-elixir
Same happened for the agility
Thanks for this
